pipeline{
  agent any
  stages{
    stage('build'){
      steps{
        sh 'echo "Build from Github"'
      }
    }
    stage('test'){
      steps{
        sh 'echo "Build from Github running on `hostname`"'
      }
    }
  }
}
